### ISSUE TITLE
further refactor of athena load code

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1310]
Some minor improvements have been discussed to be implemented to athena load code, https://github.com/ministryofjustice/data-platform/tree/main/containers/daap-athena-load/src/var/task

## Problems
- Two successive loads could conflict with each other due to sharing the state of the raw data table
- There is a case where we catch ClientError's other than not found. This multiplies the possible scenarios and shouldn't be needed - if we get another kind of ClientError we should let it fail and debug the code
- We are unsure if the scenario in L111 create_curated_athena_table is required. It looks like this covers a real possibility but there is some redundancy in the code between branches.

## Suggested solution
- [x] add random string to end of raw table name to protect against errors if quick successive loads to the same table. (Change in data_platform_paths)
- [ ] replace try except blocks with more intuitive does_exist logic for database and tables (or factor out into a function)
- [ ] separate the code that creates the table if it doesn't exist into one if statement, and the code executes `sql_unload_table_partition` if the partition file already exists into another if statement. `refresh_table_partitions` always happens so it can go outside of the ifs.

## Acceptance criteria
- [ ] Raw table name changes each time the method is run
- [ ] No unnecessary scenarios
- [ ] All remaining scenarios are exercised by the unit tests

**Comment by MatMoore** [comment]
https://github.com/ministryofjustice/data-platform/blob/56c8a30f0d6300d2f95e3e1d5762c7c59985e256/containers/daap-athena-load/src/var/task/create_curated_athena_table.py#L111 <- version with line numbers before my refactor for path names

**Comment by MatMoore** [comment]
I think create_raw_athena_table could be changed to a context manager that handles the clean up as well. If there is any error we want to make sure the table is still removed, or we will accumulate glue tables.

Also wondering if we could restructure to infer_glue_schema as this is a complex function.

**Comment by MatMoore** [comment]
The extra case on L111 is not completely redundant. There are 5 cases:

1. Table exists and partitioned data exist -> do nothing
2. Table exists and partitioned data doesn't exist -> run UNLOAD query
3. Table does not exist and partitioned data exists -> infer schema from parquet, create table
4. Table does not exist and no partitoned data exists at all -> run CREATE TABLE
5. Table does not exists and partitioned data doesn't exist for the current extraction, BUT partitions exist for other extractions

5) is the edge case we are talking about here. Matt thinks this was added because athena won't let you run CREATE TABLE if any other partitions exist in the path you want to write to, even though the table doesn't exist.

For now I'm going to keep this in; I will just refactor the code so the if/else structure is clearer. It might be that this edge case goes away with future changes, e.g. moving to dbt or iceberg.

**Comment by MatMoore** [comment]
After further discussion, we've decided that cases iii) and v) need to be handled, but they can raise errors rather than trying to recover. If these cases happen, we can recover by calling the reload_data_product lambda.

This should reduce the complexity to 3 scenarios. There is still some incidental complexity around schema inference that will go away at the point where we add the endpoint for uploading schemas to a data product. From this point on we will just be able to fetch and validate the schema at the beginning of the athena load, and we won't need to do any schema inference in this call.
