### ISSUE TITLE
Schema Validation of Data

### ISSUE THREAD

**Issue by PriyaBasker23** [ministryofjustice/analytical-platform#1655]
When the file gets uploaded i want to check if the file is in the valid format.  This should be done after the file lands to landing bucket.  The validation should be performed before the file gets moved to raw bucket. This code would be part of Move lambda from landing to raw history 

This will take place within the new lambda added in https://github.com/ministryofjustice/data-platform/pull/1774

**Steps to do** 
1. Infer the schema using the infer schema functionality 
2. Check against the registered schema 
3. If it doesn't match, move to fail path in the data bucket `fail/{data-product}/{version}/{table}/load_timestamp={load_timestamp}/data.ext` (see https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4518707454/S3+directory+structure)
4. If it does match it will get moved to the raw location (already implemented)
5. Notification via slack or email would be implemented later. 

**Definition of Done** 
- [ ] Able to move files from Landing to raw history OR fail 
- [ ] Infer schema is possible using the common functionality in python base 
- [ ] unit test implemented

**Comment by murdo-moj** [comment]
* #1594

**Comment by murdo-moj** [comment]
We need to decide on the manner of implementation for this

**Comment by MatMoore** [comment]
We decided in the end to proceed with the infer schema functionality for validation, but we will be very permissive about the types, since there may be mismatches between the registered schema and the inferred types of the dataset. E.g. glue supports various kinds of ints, but our infer schema will just return "int".

We are planning that row by row data quality checks will be implemented later (post-alpha). So this is just about whether we accept the dataset as a whole.
