### ISSUE TITLE
Enable logging within EventBridge

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#1686]
### User Story

As a developer
I want to investigate and explore options for logging in eventBridge.
So that best i can monitor and log activity through the ingestion process

### Value / Purpose

to enable better monitoring and metrics

### Additional Information

Not much work has been done looking into logging of eventbridge rules. Would be good to explore options and whether we can follow logging patterns of other components.

### Definition of Done

- [ ] enable Apigateway to emit logs to cloudwatch
- [ ] Deploy and test if its working 
- [ ] document (confluence) options for logging in apigateway.

**Comment by MatMoore** [comment]
## Option 1: Just use metrics
EventBridge is already emitting *metrics* to cloudwatch:

Full list of metrics here:
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-monitoring.html

All metrics have the following dimensions:

EventBusName 
EventSourceName
RuleName

So we can see how many invocations are failing per minute and how many trigger the target. We could visualise this in grafana. By looking at the graph you can see if the lambda target was or wasn't invoked.

It would be useful to alert on failed invocations: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-troubleshooting.html#eb-create-alarm-broken-event-rules.

## Option 2: Add cloudtrail

It is possible to log to cloudtrail but this logs administrative actions rather than invocations of the rule, so this won't help us monitor the ingestion process.

According to https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-logging-monitoring.html you can log the following EventBridge actions as events in CloudTrail log files:

[DeleteRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_DeleteRule.html)
[DescribeEventBus](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_DescribeRule.html)
[DescribeRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_DescribeRule.html)
[DisableRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_DisableRule.html)
[EnableRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_EnableRule.html)
[ListRuleNamesByTarget](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_ListRuleNamesByTarget.html)
[ListRules](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_ListRules.html)
[ListTargetsByRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_ListTargetsByRule.html)
[PutPermission](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutPermission.html)
[PutRule](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html)
[PutTargets](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutTargets.html)
[RemoveTargets](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_RemoveTargets.html)
[TestEventPattern](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_TestEventPattern.html)

## Option 3: add cloudwatch target
You can set up cloudwatch as an additional target in the EventBridge rule: https://www.boyney.io/blog/2021-04-15-debug-eventbridge-events-with-cloudwatch

I tried this with one of the rules and ended up with this log

```
	2023-10-27T15:54:40.000+01:00

{
    "version": "0",
    "id": "3f45e050-01c1-cdb0-ed8a-1c9527a8daf4",
    "detail-type": "Object Created",
    "source": "aws.s3",
    "account": "013433889002",
    "time": "2023-10-27T14:54:40Z",
    "region": "eu-west-2",
    "resources": [
        "arn:aws:s3:::data-landing-development20231011135449285800000001"
    ],
    "detail": {
        "version": "0",
        "bucket": {
            "name": "data-landing-development20231011135449285800000001"
        },
        "object": {
            "key": "landing/test_product/v1.1/test_table/load_timestamp=20231027T145435Z/0848a01d-66e2-4095-bd59-65b701735ca6.md",
            "size": 9897,
            "etag": "b09340a29271c08112440615b44594ec",
            "sequencer": "00653BCF309212C980"
        },
        "request-id": "4XHDXYMT22V1T1QV",
        "requester": "013433889002",
        "source-ip-address": "51.14.4.225",
        "reason": "POST Object"
    }
}
```

This tells us that a rule executed, but it doesn't guarantee that the other target was invoked successfully, and it doesn't log out any information we wouldn't already know from the s3 cloudtrail. So I don't think this is actually useful to us.

**Comment by MatMoore** [comment]
We've decided that Options 2 & 3 do not add any value right now, so we can close this ticket off.

The next step is to look into how we handle failure modes of the 2 eventbridge rules. This may involve responding automatically to alerts triggered by those cloudwatch metrics, but it doesn't have to be. I'll raise new tickets for this this afternoon.
