### ISSUE TITLE
Add versioning for major/breaking changes

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#2107]
### User Story

As a data producer
I need my data to be upversioned when i make a major (breaking) change to my table schema
So that consumers of my data can point their downstream processes at the latest version

### Value / Purpose

Implementation of data product versioning, enabling management of breaking changes to data products.

### Hypothesis

If we make a major change for a schema
Then the parent data product will be up-versioned and created as a new version of the database in athena

### Proposal

The copying of data and creation of a new data product version should be handled through the versioning module.

This will need to be added to the daap-update-schema lambda handler so that the expected behaviour for the data happens on a major schema update

### Additional Information

This ticket is dependant on https://github.com/ministryofjustice/data-platform/issues/1797 so we have version suffixes on databases/data products

### Definition of Done

- [x] Another team member has reviewed
- [x] Tests are green

**Comment by YvanMOJdigital** [comment]
Do first: ministryofjustice/data-catalogue#85

**Comment by MatMoore** [comment]
Tom's related PR is almost done (draft here https://github.com/ministryofjustice/data-platform/pull/2363) so I'm going to start looking into this now. The scope of the ticket needs to be refined though as major versions are implemented, we have just skipped over the question of whether we copy data to new major versions.

Slack thread where we talked about versioning and splitting data/metadata operations https://mojdt.slack.com/archives/C03QZ776JVA/p1699959917928289

Version flow diagram https://dsdmoj.atlassian.net/wiki/spaces/DataPlatform/pages/4571726228/Version+Flow+diagram

Assumptions:
1. Deleting tables deletes data from all versions (already implemented by @mitchdawson1982)
2. A major version update may or may not populate data for tables that have changed in some way (let's see what we can do)
3. A major version update will preserve data for tables that haven't changed

**Comment by MatMoore** [comment]
Preserving data from unchanged tables may not be necessary... but it makes the update process simpler, because it means that the user has to load a new snapshot only for the table that they changed, rather than loading a new snapshot for everything.

Some different scenarios:

1. User removes a column. In this case we *can* use the new metadata with the old parquet files.
2. User removes an entire table. In this case we *can* copy the existing schemas
3. User changes a column data type. In this case we *cannot* use the new metadata with the old parquet files, as we would get an athena error

The following scenarios are minor updates so will not be affected by this ticket:
1. Adding a column
2. Adding a table
3. Changing descriptions for a column
4. Changing product level metadata

**Comment by MatMoore** [comment]
**Question:** Do we need to create the glue database right away following an update?

- If so, then it is probably the same amount of work to populate historical tables as to leave them empty until the next athena load.

- If not, then we may have a period of time where the metadata is in the catalogue but the tables don't exist, which is more confusing for users. This scenario can also occur when new schemas are added but is less likely to be an issue in that case. 

**Answer:** Yes, because otherwise the latest version of the data product will not work with the preview endpoint, and if a data consumer sees that a new version exists, they would expect populated tables to be available and that tools are able to access them. At the very least, tools shouldn't *break* due to missing tables.

**Comment by MatMoore** [comment]
Scenario from a consumer perspective:

- Data owner updates a schema
- Consumer notices that a major update is available
- Consumer tries to use the new version

**Maybe new major versions need to go through some kind of draft state until the first athena load has completed successfully? Until then, we don't send it to the catalogue and don't send out notifications.**

**Comment by MatMoore** [comment]
[Proposed behaviour for different scenarios](https://miro.com/app/board/uXjVPLs45lw=/?moveToWidget=3458764570135507896&cot=14) (TBC)

Can split these scenarios into

A. cases where we can create the new table using historical data (e.g. when deleting a table)
B. cases where a new snapshot will be required before the new table is "ready"

I think case A does exist, so I can start looking at this later this afternoon.

Case B needs some further refinement. Current proposal:

- the data owner could pass a flag indicating a new snapshot will follow
- if the flag is present, we store it as part of the table schema
- we could use the presence of the flag to prevent versions of the data product that are pending a new snapshot from being exposed to data consumers via the catalogue

**Comment by MatMoore** [comment]
First step to move athena code out of athena load: https://github.com/ministryofjustice/data-platform/pull/2421
