### ISSUE TITLE
 ✨ Read / write to external bucket in create-a-derived-table

### ISSUE THREAD

**Issue by gwionap** [ministryofjustice/analytical-platform#2850]
### Describe the feature request.

We would like the ability to specify an external s3 location for models in create-a-derived-table that are designed to back apps developed on the AP. We can do this in a model config, on locally, but the github action that runs `dbt build` doesn't have sufficient AWS permissions to write to the S3 bucket specified.

### Describe the context.

OPG have been developing a dashboard application on the AP to be hosted on the CP. This app needs access to specific tables generated by create-a-derived-table.

### Value / Purpose

This feature would help adhere to the security principle of least privilege as the application would only have access to its own dedicated S3 bucket without exposing the `mojap-derived-tables` e.g. perhaps allowing the app to list other tables present in the bucket.

### User Types

create-a-derived-table users, OPG data scientists

**Comment by jhpyke** [comment]
Hi,

This is definitely doable - The Create-A-Derived-Table policy permissions boundary is [defined here](https://github.com/ministryofjustice/data-platform/blob/4808b0d94355650f81687c8e627f9cea35d02117/terraform/aws/analytical-platform-data-production/create-a-derived-table/iam-policies.tf#L1-L77), including the specification for which buckets it has write access over. To facilitate this, you can either specify the bucket(s) you'd like to see added to the write permissions so we can raise a PR with the change, or you can just directly raise a PR with the changes you'd like to see. In the interest of minimal permissions we'd like to continue to scope these permissions to specific named buckets rather than generically over buckets in the account.

Can I just check - what's the rationale for deviating from the current domain based access model that Create-A-Derived-Table currently operates on? Obviously placing items in other buckets is a deviation from that - we've supported dumping to buckets _in addition_ to writing to the main bucket before, is that what'll be happening in this case, or is this seeking to _exclusively_ write to an OPG bucket instead of `mojap-derived-tables`

Thanks,
Jake

**Comment by gwionap** [comment]
Thanks Jake. I'll have a look and see if I can raise a PR with the needed changes.

The specific reason for deviation here is for apps developed on the AP. Essentially, this is me being super cautious, and wanting apps that need access to an Athena table to only need / have access to their own S3 bucket, rather than the shared S3 bucket. This is to minimise accidental permission sets being incorrect or e.g. the app being given permission to list objects in `mojap_derived_tables` and therefore objects outside its domain. If we want to still have a table in `mojap_derived_tables` we could make sure the one dumped in the OPG bucket is a copy of an existing table.
