### ISSUE TITLE
☸️ EKS Cluster Consolidation

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/analytical-platform#2943]
> [!NOTE]  
> If we are looking at SageMaker etc in 6+ months then this should be done.

> [!IMPORTANT]  
> If we are looking at them soon then this does not need to be done. 

### Brief summary of what this Epic is

We currently run a number of EKS clusters which are about to go into extended support - 31st January. 

Additionally they use Flux for deployment and we would like to stop using this technology. 

<img width="1040" alt="Screenshot 2024-01-15 at 11 55 27" src="https://github.com/ministryofjustice/data-platform/assets/26419401/fb62f282-b368-4e6c-9305-e47f3d279f0b">

# Issues in Epic
- [x] #2945
- [x] #2946
- [x] #2947
- [x] #2948
- [x] #2949
- [x] #2950
- [x] #2943
- [x] #1950
- [x] #1371

**Comment by julialawrence** [comment]
I think we should do this unless the horizon for new tooling is less than 90 days because 
1. We don't know that SageMaker will be the tool of choice although we strongly suspect it.
2. Any migration to new tooling offerings will almost certainly be gradual rather than shut-off-turn-on which means maintaining both environments out of the same cluster will make things easier
3. The window between "we're starting adoption of new tooling" vs "we're making new tooling available to users" is very likely to take us beyond the 6 months window anyway.
4. We anticipate being able to move containerised workloads to CP at some point and kicking the tires on migration would probably be a good thing
5. With EFS being the unknown, I'm not sure the effort involved is actually that big so therefore narrower window to make it worth it.

**Comment by julialawrence** [comment]
We will deliver this work as part of the refined architecture for AP.
