### ISSUE TITLE
Add 3 additional filters to front end

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/analytical-platform#2961]
Removing as this duplicates #3047 

The following filters to be implemented in the front end:

Source system or service name (acronym OR full name) _- eg. NOMIS / National Offender Management System, LPA / Lasting Power of Attorney
Data location/availability (AP, other platform,...)
Sensitivity level

Subdomain not to be implemented in this ticket

**Comment by alex-vonfeldmann** [comment]
**User stories:** 

- As a user, I want to be able to search for all data that matches a specific topic, so I can see whether and how much relevant data exists (eg. “rehabilitation science”). 
- As a user, I want to be able to search for data supporting a specific query/insight/reporting need, so can see whether and how much relevant data exists (eg. “forecast prison occupation”).  
- As a user, I want to be able to filter down topic and query search results by effective and easy to recognise filters, so I can narrow down the results list to a manageable subset.

**Comment by alex-vonfeldmann** [comment]
@seanprivett the simplified 'high ranked' filter list for UR purposes could look something like his: 

- Domain
- ~~Subdomain~~ - THS WILL BE A SEPARATE SPIKE
- Source system or service name (acronym OR full name) _-  eg. NOMIS / National Offender Management System, LPA / Lasting Power of Attorney 
- Data location/availability (AP, other platform,...) 
- Sensitivity level

I imagine source system or service name could be delivered as tags rather than as filter UI components

I expect users will want additional filters to the above which we will hear about in UR

I'm not sure the current options for the search result sort is right ('Relevance / Ascending / Descending'). 'Recently created' and 'Recently updated' might be better candidates. 'Relevance' might be useful if someone can explain to me how this is actually modelled and ranked? 

I'm not sure that we can deliver the two use cases above if we do not massage the metadata content (ie. adding proper descriptions, tags, etc)

**Comment by jemnery** [comment]
First stab at subdomains from refinement:

```
HMPPS
  -- prisons
  -- probation
HMCTS
  -- magistrates courts
  -- crown courts
  -- family courts
  -- civil courts
OPG
  -- Lasting power of attorney
  -- supervision orders
HQ
  -- people
  -- finance
  -- performance
  -- estates
LAA
  -- legal aid
  -- public defender
  -- civil legal advice
CICA (no subdomains)
```

**Comment by alex-vonfeldmann** [comment]
+ CICA (as a domain)
