### ISSUE TITLE
 ✨ Manage AWS Parameters (or secrets) via AP console

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [ministryofjustice/analytical-platform#3858]
### Describe the feature request.

Allow AP users to Manage AWS Parameters (or secrets) via AP console

### Describe the context.

Users used to be able to manage AWS Parameters via [AP console](https://user-guidance.analytical-platform.service.justice.gov.uk/parameters.html#storing-a-parameter) but it seems this ability has been removed. Instead it seems users now have to raise a support request when they need a new parameter created.

Links:
- [Slack]9https://mojdt.slack.com/archives/C8X3PP1TN/p1711019078612949)
- [Support request](https://github.com/ministryofjustice/data-platform-support/issues/507)

### Value / Purpose

Airflow pipelines sometimes need to access parameters/secrets: https://user-guidance.analytical-platform.service.justice.gov.uk/parameters.html#example-airflow-uses-parameters. Apps also used to access these parameters but not sure if this still applies with the new solution

### User Types

AP users

**Comment by SoumayaMauthoorMOJ** [comment]
Please keep this open. There is a work-around but it requires users raising a request and engineers manually creating the secrets on behalf of users so it's not ideal.

**Comment by mshodge** [comment]
Just to add, this would be extremely useful - have had to ask @SoumayaMauthoorMOJ to help add one for me as I don't have the perms.

**Comment by SoumayaMauthoorMOJ** [comment]
Sorry can't help you mate - don't have permission either

**Comment by michaeljcollinsuk** [comment]
Old PR where this functionality was removed https://github.com/ministryofjustice/analytics-platform-control-panel/pull/1129

From reading through the old PR and associated ticket, it seems that it was removed as part of the app migration to Cloud Platform, which meant that app secrets are stored in GitHub rather than AWS parameter store. However, managing airflow secrets does not seem to have been considered at the time, therefore I plan to restore the feature but limit the secret type to airflow only.

**Comment by SoumayaMauthoorMOJ** [comment]
Hey @michaeljcollinsuk thanks for clarifying. Do you know why app secrets are stored in GitHub rather AWS parameter store? It makes it hard to share with team members if they want to use the secret outside of github, so I tend to use Github secrets only for personal projects

**Comment by michaeljcollinsuk** [comment]
@SoumayaMauthoorMOJ it was before I started here so not 100% clear, but from reading the old tickets it seems the decision to store app secrets in GitHub was due to complications reading them from AWS parameter store in the deployment process after apps were migrated to the Cloud Platform. There is an old [ADR](https://silver-dollop-30c6a355.pages.github.io/documentation/30-architecture/40-architecture-decision-records/118-ADR118-use-github-secrets-for-app.html#adr118-use-github-secrets-for-apps) about this decision although admittedly it doesn't contain much further information.

**Comment by SoumayaMauthoorMOJ** [comment]
OK thanks for clarifying, and it's reassuring it's only for apps

**Comment by michaeljcollinsuk** [comment]
Closing as complete - Control Panel can now be used to add parameters to AWS Parameter store for use with Airflow dags, via the [Parameters menu tab](https://controlpanel.services.analytical-platform.service.justice.gov.uk/parameters/):

![Image](https://github.com/user-attachments/assets/6965eed4-9543-4b6f-b4ea-0509c42da150)
