### ISSUE TITLE
 ✨ Bedrock in Analytical Platform Apps

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#4311]
### Describe the feature request.

Raising on behalf of @jtattersall09403

 Request for the Prison Data Science team to have access to use the Claude generative AI models _**in Apps**_. Ideally Claude Sonnet and Claude Haiki; if that's not possible then the older Claude 2.1 model would be OK.
 To meet the requirement 2 in the context section below, we need to be able to provide Bedrock access to three existing apps in production:
 
- safety-diagnostic-tool https://github.com/ministryofjustice/safety-diagnostic-tool
- bentham-app https://github.com/ministryofjustice/bentham-app/tree/c313a91cad65b2dd27bdb21c564a38224e14ab49
- prison-visitor-app https://github.com/ministryofjustice/prison-visitor-app

### Describe the context.

Four current projects, and more in the pipeline. All use sensitive data; CDDO have agreed the use of Bedrock in the EU (Frankfurt & Paris currently, London, Ireland to come) for these purposes, subject to the completion of a DPIA. For all projects, we need to be able to:

1. Test the capabilities of the different models. We need to be able to answer questions like, 'how good each Claude model at summarising intelligence reports' (or classifying casenotes, or classifying text messages, or allocating a 'reason' tag to incident reports). This would be via jupyter notebooks on the AP, using AP data (e.g. casenotes from the nomis pipeline, or Seized Media Database data from s3).
2. Run the models for inference in production. If the models meet our evaluation thresholds, we then want to be able to use them in production. In practice, this means things like the below (which are in order of priority):
- Calling the models via API from a deployed R Shiny application, hosted on the cloud platform

Project details can be found in the [original feature request](https://github.com/ministryofjustice/analytical-platform/issues/4222)

### Value / Purpose

We have extensively tested methods that are possible using current infrastructure (e.g. huggingface open source models). All methods fall short of what is needed for these projects. Testing on dummy/synthetic data suggests that the Claude models will substantially outperform these simpler alternatives, unlocking a huge amount of value for our frontline users. All four projects (and others like them that we will do in future) will save a huge amount of time for frontline users, meaning they will spend less time on paperwork and more time running our prison system safely and effectively.

### User Types

Data scientists in Prison Data Science

**Comment by julialawrence** [comment]
Timelines copied from [here](https://github.com/ministryofjustice/analytical-platform/issues/4222#issuecomment-2088428038):
> Just to add after our call just now. In priority order, we need to be able to:
> 
> 1. Run analysis manually on the AP (e.g. in Jupyterlab) using LLM models hosted in Bedrock. **8th May deadline** to enable us to meet our 'mid May' deadline for analysis outputs with customers.
> 2. Schedule scripts that call Bedrock LLMs, using Airflow. Would need this by **mid June** to start implementation.
> 3. Call Bedrock LLMs in real time from AP apps deployed on the cloud platform. More flexible on timelines - end of June perhaps? Initially these apps would be:
> 
> * safety-diagnostic-tool https://github.com/ministryofjustice/safety-diagnostic-tool
> * bentham-app https://github.com/ministryofjustice/bentham-app/tree/c313a91cad65b2dd27bdb21c564a38224e14ab49
> * prison-visitor-app https://github.com/ministryofjustice/prison-visitor-app

**Comment by carlosMoJ** [comment]
This looks great, and I would appreciate if some more apps (not yet in CP) could be added. I would appreciate if this feature request could include access to the Titan Text Express model as well, which is the one I am aiming to customise as part of my MSc/Apprenticeship final project. the region for that model should be (at this stage) North Virginia (as it supports customisation). What I envision for my final project is:

- A console app which will be used to customise the Titan Text Express model 
  - costs for customising a model/storing the customised model are not very high, and if due to time constraints I cannot prepare the data to customise the model, I can potentially use some 'fake' data from hugging face or something like that, so I can present on the dissertation.  
  -   This can potentially be implemented as part of the web API
- A web API to access Amazon Bedrock
  - Due to the costs of inferring from a customised model, I may work with a proof of concept and just infer from the 'normal' model (Titan Text Express)
  - I will also explore the API and check how to enable/disable programmatically the provisioned throughput, to. keep costs at a minimum, if/when exploring inference from a customised model. 
- A simple website to interact with the API and as a front-end for users

Please feel free to get back to me with any queries you may have.

thanks!!

**Comment by carlosMoJ** [comment]
Hi team! any news on this? thanks!!

**Comment by michaeljcollinsuk** [comment]
> Hi team! any news on this? thanks!!

Hey Carlos, we have a draft PR to enable this, which we hope to be ready to test soon. Will keep you updated.
