### ISSUE TITLE
Airflow Migration: Investigate copying CloudWatch logs to another account

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#478]
## User Story

In order to make Airflow migration as hassle-free as possible, we need to copy cloud watch logs from the Data Production account to Modernisation Platform account. While not strictly needed, the workaround required in order to avoid having to rerun many many jobs and eating up unneeded resources is quite work- and comms-intensive and should be avoided if possible.

## User Type(s)

Airflow Engineers, Ops Engineers

## Value

Save migration time and impact if we can simply recreate a like-for-like set-up that preserves run histories.

### Proposal

Since MWAA setup doesn't offer an option to read from cloudwatch logs cross account, we want to investigate copying run logs into MP as part of the migration.
We need to investigate if this is possible, perform a small test and also preferably verify that MWAA can consume the new logs and interpret them correctly. (Potentially,  to avoid overlap, an instance of MWAA can be set up in Sandbox account pointing to a copied stream and see if it's able to function as expected.)

## Definition of done

- [ ] Investigation performed
- [ ] Outcomes captured in a document
- [ ] Determine if copying is possible
- [ ] Make a recommendation about a way forward
- [ ] Raise follow-on stories

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jacobwoffenden** [comment]
Evaluation of Production Airflow's CloudWatch logs (as of 01/06/2023 12:30 GMT):
| Name | Size | Streams |
|:---:|:---:|:---:|
| airflow-prod-DAGProcessing | 214.09 GB | 96 |
| airflow-prod-Scheduler | 87.6 GB | 100+ |
| airflow-prod-Task | 12.29 GB | 100+ |
| airflow-prod-WebServer | 1.69 GB | 100+ |
| airflow-prod-Worker | 824.07 MB | 100+ |

**Comment by jacobwoffenden** [comment]
I cannot find a native way to upload streams, only download

I could perhaps write something to programatically loop over each log group and stream, pull the events, and put them in a new group and stream, but that might be a lot of engineering and time to process 300GB+ of data

The only possible suggestion I could make is that we point the new Airflow in Modernisation Platform at CloudWatch in Data Production, which we decided against early on

**Comment by jhpyke** [comment]
So I will say loss of logs isn't a blocker as such - Although there's user action we would require in the event the logs can't be preserved, we went through that process with the last versioning upgrade so we understand what the implications will be that we will need to play around. Namely

- Users by default will not be able to access logs of prior runs. We will either want a way for them to explore those encoded in IAM, or to communicate this fact to them in advance so they can account for it.
- DAGs take a `start_date` variable. If they lack a run history, they will try and schedule all runs it views itself as having 'missed' since the last run (which may number in the 1000s). This is solved by updating (or having the user update) the start date to either the switchover date or a date shortly before it, in order to limit catchup runs
- Existing (large) log groups may need to be retained for auditing purposes, if so we need to understand that from users/security team.

If there's a viable and straightforward way to port it over (which it sounds like there isn't) we'd want ideally to do that, but as I say the workarounds are certainly very doable, particularly given this caught us off guard last time and we were able to recover successfully within about a day and change as a team of 2. With proper preparation this is manageable.

**Comment by julialawrence** [comment]
We decided against it because I don't think it's actually possible to point at logs cross account.

I think if Jacob says it's not a blocker, it's not a blocker and we find a way to mitigate and move on.

**Comment by jacobwoffenden** [comment]
After seeing the output of this [plan](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/5144082620/jobs/9259920812?pr=2402), I thought it might may be possible to specify an ARN

```terraform
      + logging_configuration {
          + dag_processing_logs {
              + cloud_watch_log_group_arn = (known after apply)
              + enabled                   = (known after apply)
              + log_level                 = (known after apply)
            }

          + scheduler_logs {
              + cloud_watch_log_group_arn = (known after apply)
              + enabled                   = (known after apply)
              + log_level                 = (known after apply)
            }

          + task_logs {
              + cloud_watch_log_group_arn = (known after apply)
              + enabled                   = (known after apply)
              + log_level                 = (known after apply)
            }

          + webserver_logs {
              + cloud_watch_log_group_arn = (known after apply)
              + enabled                   = (known after apply)
              + log_level                 = (known after apply)
            }

          + worker_logs {
              + cloud_watch_log_group_arn = (known after apply)
              + enabled                   = (known after apply)
              + log_level                 = (known after apply)
            }
        }
```

However, [as documented in CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-mwaa-environment-moduleloggingconfiguration.html#aws-properties-mwaa-environment-moduleloggingconfiguration-properties)

> CloudWatchLogGroupArn is available only as a return value, accessible when specified as an attribute in the [Fn:GetAtt](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-mwaa-environment.html#aws-resource-mwaa-environment-return-values) intrinsic function. Any value you provide for CloudWatchLogGroupArn is discarded by Amazon MWAA.

Based on that, I will close this ticket and use the workarounds from @jhpyke's comment
