### ISSUE TITLE
SPIKE - Terratest API Testing

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/analytical-platform#533]
## User Story

As a developer
I need smoke tests/unit tests
So that I can streamline my development workflow and have confidence in my product

## Description 
1. Explore  local stack testing 

We want our API to be tested. We've done this before with [Localstack](https://github.com/localstack/localstack), so this seems the easiest approach to start with
https://github.com/ministryofjustice/data-engineering-pulumi-components/tree/main/tests_end_to_end/localstack_tests
https://github.com/ministryofjustice/data-engineering-pulumi-components/blob/main/.github/workflows/test_localstack.yaml

The previous implementation was using Pulumi, but we currently use terraform to deploy resources, so the implementation will be slightly different (with the same idea). Here's a terraform specific guide which suggests using a module called tflocal to build the resources, after which pytest could be used as above https://www.tinfoilcipher.co.uk/2022/05/14/simulating-aws-terraform-builds-with-localstack/

2. Explore terratest  
3.Pick a suitable option for implementation 

## Definition of done

- [ ] Github workflow created which executes Localstack tests
- [x] Make  end to end test for one api end point

**Comment by MatMoore** [comment]
Here is a spike that deploys to data-engineering-sandbox: https://github.com/ministryofjustice/data-platform-terraform-modularisation-spike

We used this environment for the spike so that we could apply terraform and experiment locally, without having to go through modernisation platform's deployment pipelines/ask for more permissions.

Here is a draft PR to integrate the api-core module back into the modernisation-platform-environments repo: https://github.com/ministryofjustice/modernisation-platform-environments/pull/3532 - this is just to show what it will look like; actually merging this will be part of the implementation tickets.

**Comment by MatMoore** [comment]
I've now completed the end to end test for the upload data endpoint. See https://github.com/ministryofjustice/data-platform-terraform-modularisation-spike for more info.

We decided not to implement the github workflow as part of this ticket, and not to look at localstack just yet.
