### ISSUE TITLE
🐞 Sentry alerts relating to Helm errors in Control Panel

### ISSUE THREAD

**Issue by michaeljcollinsuk** [ministryofjustice/analytical-platform#5529]
### Describe the bug.

There are a lot of Sentry alerts for Control Panel being triggered relating to Helm errors. Some of these have a very high number of alerts ([such as this one](https://ministryofjustice.sentry.io/issues/3686689878/?project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0)).

This is a link to Sentry, filtered by the number of events where you will see the majority are Helm related https://ministryofjustice.sentry.io/issues/?project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-list&sort=freq&statsPeriod=14d

Although these errors are not new and don't appear to be affecting the functionality of the site, they make our Sentry very noisy.

### To Reproduce

Needs further investigation to determine the exact cause of the errors, but they often appear related to Tool deployments and releases.

It is also likely that a lot of the errors are related to each other, where one error triggers another.

### Expected Behaviour

We should debug the errors and either:
1. Fix the cause of the error where possible
2. Handle expected Helm errors more gracefully, so that they do not reach Sentry if they are not causing any issues with functionality

### Additional context

- A lot of the errors seem to come from the `cpanel-worker-*` pods rather than the core app.
- Some of the errors may relate to the bug where initially attempting to deploy a new tool release.

**Comment by michaeljcollinsuk** [comment]
Example sentry alerts, all related, that were triggered after attempting to deploy a tool:

https://ministryofjustice.sentry.io/issues/5974332397/?environment=prod&project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=0

https://ministryofjustice.sentry.io/issues/3941210337/events/4ad34c18f57042a78c481ec45ec6ef19/?project=5606313

https://ministryofjustice.sentry.io/issues/3686689878/?environment=prod&project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=2

**Comment by jamesstottmoj** [comment]
The two main helm errors are [this](https://ministryofjustice.sentry.io/issues/5158546070/?environment=dev&project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0&utc=true) and [this](https://ministryofjustice.sentry.io/issues/6062370688/?environment=dev&project=5606313&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=4&utc=true)

The first is a result of installing a new tool. The second happens when installing a new tool over an old one. The options for resolving these would be to dig into why helm is throwing these errors at us or to check the error string for these 2 and don't throw the helm error as they don't seem to cause any issues when deploying the tool.
