### ISSUE TITLE
🕸 Register CaDeT tables in APC Glue catalog so the data can be queried

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/analytical-platform#5859]
### User Story

While we are replicating the bucket data across accounts to allow CaDeT data to be visualised via QS, we also need to replicate the Glue metadata in order to make the data usable and allow access management via LF.

The metadata should be identical to the Glue information held in the origin account.

### Value / Purpose

Replication of metadata rather than doing a bulk extract and copy would ensure greater fidelity, and allow more regular synchronisation when new data is added or old is removed. While copying metadata could be a viable backup plan, CaDeT was partially selected because its structure makes recreation of metadata via crawling a quicker and more robust approach.

### Useful Contacts

Jacob Hamblyn-Pike, Julia Lawrence

### User Types

Data Engineers, AP Customers

### Hypothesis

Regularly running the crawler would allow us to maintain the best level of parity with the orgin bucket for QS users.

### Proposal

1. Using terraform, design and implement a glue crawler which replicates CaDeT metadata in the Analytical Platform Compute Ireland region.
2. Validate the output against the original metadata
3. Agree crawling schedule

### Additional Information

This story is hinging on the assumption that a crawler is all that is needed to recreate the metadata. If this turns out to not be the case, we will need to pivot to a different approach. Two backup options are extracting and coping metadata and running CaDeT workflows twice. Once against the origin bucket and once against the new bucket.

### Definition of Done

- [ ] Implement proposal
- [ ] Code reviewed
- [ ] Team reviewed
- [ ] Follow-on stories captured

**Comment by tom-webber** [comment]
#5958 adds CaDeT replication to the `analytical-platform-compute-development` account to allow manual / more flexible changes within the account for testing out crawler / metadata setups.

This requires minor changes to the AP-compute MP environments to account for this change. After that we will be testing out crawler setups ([see doc](https://docs.google.com/document/d/1h6lft2IWB2eImFf6_Vd6DOFkLU-FNZIC0yJncmCimOc/edit?tab=t.8ucjz23wthjg) and [discussion](https://mojdt.slack.com/archives/C04M8224WCV/p1730468013872439))

**Comment by tom-webber** [comment]
Requirements for setting up crawlers:
- IAM role set up with adequate glue permissions. Default (set up via console) is: 
   - [AWSGlueServiceRole](https://docs.aws.amazon.com/aws-managed-policy/latest/reference/AWSGlueServiceRole.html) 
   - and a policy granting `"s3:GetObject"` and `"s3:PutObject"` within database directory
- IAM role is [added as a Lake Formation Administrator](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf)
- Databases are created in Glue 
   - (naming convention? `{domain}_{database_name}`?
- How do we control table naming patterns? (discarding the `database_name_` prefix that would automatically be generated from dbt structured CaDeT output)
   - [the CaDeT list of database names](https://github.com/moj-analytical-services/create-a-derived-table/blob/4b8fefa23194742121ae1eb43b8deaf5e4290080/scripts/source_database_names.txt#L4) is updated weekly via the [update-source workflow](https://github.com/moj-analytical-services/create-a-derived-table/blob/4b8fefa23194742121ae1eb43b8deaf5e4290080/.github/workflows/update-source.yml) ([see docs](https://user-guidance.analytical-platform.service.justice.gov.uk/tools/create-a-derived-table/source-and-ref-functions/#adding-a-new-source) or [CONTRIBUTING.md](https://github.com/moj-analytical-services/create-a-derived-table/blob/4b8fefa23194742121ae1eb43b8deaf5e4290080/CONTRIBUTING.md#update-sources))

**Comment by AntFMoJ** [comment]
Initial results of setting up the crawlers:
- Unpartitioned Hive tables were successfully crawled and tables were created
- Partitioned Hive tables were not able to be crawled properly
- Iceberg tables were also not able to be crawled properly

Testing scripts were set up to pull the Glue metadata for data sources in APDP and push the metadata to the Glue catalog in APC-development. Testing was:

 - successful when creating a partitioned Hive table in APC-development, after running `MSCK REPAIR TABLE <table_name>` to handle the partitions in the new table
 - unsuccessful when creating Iceberg table.

Next step will be to revisit Glue crawlers for Iceberg data sources by referring to [this documentation](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-crawling.html#aws-glue-api-crawler-crawling-IcebergTarget).

**Comment by tom-webber** [comment]
Crawling Iceberg Tables:
- Crawling delius (contains Iceberg tables):
   - Default set up: generated 1000 tables, with metadata files and partitions becoming distinct tables
   - Explicitly setting the table level to 6 (level in bucket for the `table_name={}` directory) led to failures because files at level 8 (actual file level) are not consistently named or structured. This is because level 7 has `data/` and `metadata/` folders containing different structured files.
- [Iceberg ingestion via API](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-api-crawler-crawling.html#aws-glue-api-crawler-crawling-IcebergTarget) may be the only way to resolve the presence of different file structures with a Glue crawler, as this allows glob pattern exclusion from crawling
- Using the API still won't resolve the issue of the metadata files pointing at the source location in the data account
   - @jhpyke found that there are references in plaintext JSON files as well as in the snappy compressed AVRO files to the original S3 location of the metadata files (in the source account)

Support request raised with aws


LakeFormation Notes:
- Setting up [permissions for adding Data Lake Location](https://docs.aws.amazon.com/lake-formation/latest/dg/registration-role.html) required adding Trust Policy assumption by the `lakeformation.amazonaws.com` service to the IAM policy we wanted to use.
- Granted lake formation permission to the `manual` glue role set up for database / table / lakeformation location registration
- Creating iceberg table via the Lake Formation console (_AWS Lake Formation > Tables > Create table_) in APC-dev didn't work. It gives the following error: `AccessDeniedException (status: 400): Access denied while creating metadata file in s3`. This happens when trying to register the table from S3 location in `APC-dev` or in `APDP`.
   - The same error is encountered when trying to register the Table through the Glue console (_AWS Glue > Tables > Add table)_
   - The same error is encountered when running the [create table command via aws cli (glue)](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/glue/create-table.html) when assuming the `manual` role that registered the Data Lake Location.
   - **Note:** 'Compaction', 'Snapshot retention', and 'Orphan file deletion'  were disabled when attempting to register the table as they may cause file changes not reflective of the tables registered via CaDeT.
   -  **Note:** I didn't grant `s3:DeleteObject` permission on the `mojap-derived-tables` bucket policy of the role used to register the Data Lake Location, [even though this is recommended](https://docs.aws.amazon.com/lake-formation/latest/dg/registration-role.html).
- It looks like a 'resource share' might be a viable option ([sharing the Glue Table from the source catalogue to the destination](https://docs.aws.amazon.com/lake-formation/latest/dg/sharing-catalog-resources.html) Lake Formation), but that may require Lake Formation in the source (APDP) account.

**Comment by tom-webber** [comment]
`AccessDeniedException (status: 400): Access denied while creating metadata file in s3` was resolved by:
- Adding the sandbox and manual roles to the `mojap-compute-development-derived-tables-replication` bucket's customer-managed kms key policy
- Adding the sandbox and manual roles to the bucket policy (`GetObject`, `PutObject`, `ListBucket`)

**Comment by tom-webber** [comment]
We gave up on using crawlers and using replicated data within the destination account (`analytical-platform-compute-dev`, aka APC-dev). Instead we went back to exporting Glue catalog metadata from the source account (`analytical-platform-data-production`, aka APDP) and creating tables using this metadata within the destination account. [Prototype python scripts](https://github.com/ministryofjustice/analytical-platform-glue-catalog-transfer/tree/extract-data-from-bucket/scripts) are used to iterate over databases, and repair hive tables to restore their partitions in the new catalog (not necessary for Iceberg tables).

We managed to get this working with same-region catalog copy (Ireland -> Ireland), and also cross-region catalog copy (Ireland -> London). After `Grant`ing QuickSight user query permission via LakeFormation, we were able to query data via QuickSight in either destination region.

Remaining work:
- replicate necessary permissions in Terraform
- clear development account of manual changes
- iterate over all databases in CaDeT
- work out if the table repair function can be changed into a less 'expensive' query 
   - currently using `MSCK REPAIR TABLE` which scans all data, where it may be possible to retrieve and use partition information instead
