### ISSUE TITLE
Write tests - unit  for get glue metadata lambda

### ISSUE THREAD

**Issue by LavMatt** [ministryofjustice/analytical-platform#879]
Investigate how best to automate testing of lambda containers using pytest.

**Comment by MatMoore** [comment]
I'm going to try and look at this today.

**Comment by MatMoore** [comment]
I think we will want to use https://pypi.org/project/moto/ for mocking AWS services.

I will see if there are any AWS recommendations for structuring the tests with container lambdas, but failing that I'll just introduce a test directory that doesn't get copied into the docker image.

**Comment by MatMoore** [comment]
For reference, here are AWS examples (using moto)

https://github.com/aws-samples/serverless-test-samples/tree/main/python-test-samples

**Comment by MatMoore** [comment]
I can't edit the description, but here is my proposed scope for this ticket.

### Acceptance criteria

- There is at least one unit test we can use as an example
- Tests are documented in the readme
- The containers workflow should run the unit tests, and fail the workflow if tests fail

### Proposed solution
Add daap-get-glue-metadata/tests/ directory.

In tests/requirements.txt we need pytest, moto, plus the existing dependencies (boto3 and botocore)

I noticed that for the image itself we are not pinning the versions for the whole dependency tree. I propose that for now we follow the same approach for the test requirements, and we can perhaps investigate making builds more reproducible as a separate task later on.

In unit/tests we should create mock_test.py, similar to https://github.com/aws-samples/serverless-test-samples/blob/main/python-test-samples/apigw-lambda/tests/unit/mock_test.py

Since at the moment, the lambda only handles a success case (200 response), we can just write one test, that stubs out glue, and ensures that the lambda passes through the response in the correct format if the glue client does not error.

If this ticket lands before https://app.zenhub.com/workspaces/data-platform-labs-6439239ff652d87aef65297a/issues/gh/ministryofjustice/data-platform/686 then we can add extra tests as part of that one.

### Unanswered questions
Get glue metadata does not depend on any shared libraries, but others depend on code that is currently distributed in the daap-python-base image.

If we are running the tests outside of a container, we need to make sure the shared libraries are on the python path  (option 1)

Alternatively, we could run the tests from inside the container, so that all the shared files will be there (option 2). For example, we could create a docker-compose file that mounts the test files into the lambda container.

I think it would be easiest to go with option 2, but if anyone has any thoughts on this let me know.
